SheltersScreen with button to Map and return button
MeowdoptMe/MeowdoptMeApp pull request #19
Opened 2023-05-04 10:20 UTC by trissve

:rocket: roket

2023-05-04 10:34 UTC, trissve commented
https://user-images.githubusercontent.com/86602714/236180391-bffab8b5-d949-43ad-a262-0b7310f426dc.mp4

2023-05-04 13:05 UTC, tjzel requested changes

2023-05-04 13:05 UTC, tjzel commented on MeowdoptMeApp/src/SheltersScreen.tsx
> +import {ScreenContext} from './Context';
Please remove unnecessary imports.

2023-05-04 13:05 UTC, tjzel commented on MeowdoptMeApp/src/SheltersScreen.tsx
> +  const [page, setPage] = useState(0);   // 0 to sheltersList, 1 - mapa
Making it a numerical value and then add a comment is not the best option here - code should be as self explanatory as possible. Consider making the state a string, for eg. `const [page, setPage] = useState('list')` or making it a boolean value: `const [isSheltersList, setIsSheltersList] = useState(true)`.

2023-05-06 10:29 UTC, trissve commented
https://user-images.githubusercontent.com/86602714/236618790-69d0a783-98e1-4f3c-82ed-c57e8aca1f09.mp4

2023-05-06 18:10 UTC, tjzel approved these changes
:clap:

2023-05-08 07:54 UTC, merged